name: Run DBT Models on GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # dbt install
    - name: Install DBT and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-bigquery google-cloud

    # - name: Set up Google Cloud service account
    #   run: |
    #     echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/service_account_key.json
    #     gcloud auth activate-service-account --key-file=/tmp/service_account_key.json

    # - name: Set up environment variable for DBT profile
    #   run: |
    #     echo "keyfile: /tmp/service_account_key.json" >> ~/.dbt/profiles.yml
    #     echo "project: your-gcp-project-id" >> ~/.dbt/profiles.yml
    #     echo "dataset: your_bigquery_dataset" >> ~/.dbt/profiles.yml
    #     echo "threads: 1" >> ~/.dbt/profiles.yml
    #     echo "location: US" >> ~/.dbt/profiles.yml

    # - name: Run DBT models
    #   run: |
    #     dbt run --profiles-dir ~/.dbt

