name: Run DBT Models on GCP

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Install DBT and dependencies
    - name: Install DBT and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-bigquery google-cloud

    # Authenticate with Google Cloud using the Service Account Key
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/867824075452/locations/global/workloadIdentityPools/dbt-wif-github-action-pool/providers/github 
        service_account: dbt-wif-p@dbt-learning-bq.iam.gserviceaccount.com

    # Set up Google Cloud SDK using setup-gcloud@v2
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      # with:
      #   project_id: ${{ secrets.GCP_PROJECT_ID }}  # Ensure GCP_PROJECT_ID is set as a secret or environment variable
      #   export_default_credentials: true

    - name: Set up DBT profile
      run: |
        mkdir -p ~/.dbt
        cat > ~/.dbt/profiles.yml <<EOF
        dbt_github_action:
          target: dev
          outputs:
            dev:
              type: bigquery
              method: oauth
              project: ${{ secrets.GCP_PROJECT_ID }}
              dataset: ${{ secrets.GCP_DATASET_ID }}
              threads: 1
              location: us-central1
        EOF

    - name: Install dbt dependencies
      run: |
        dbt deps
    
    - name: run dbt debug
      run: |
        dbt debug --profiles-dir ~/.dbt
    
    - name: Run dbt test
      run: dbt test --profiles-dir ~/.dbt
