name: Run DBT Models on GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install DBT and dependencies
    - name: Install DBT and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-bigquery google-cloud

    # Install Google Cloud SDK (gcloud) for authentication
    - name: Install Google Cloud SDK
      run: |
        curl https://sdk.cloud.google.com | bash
        source $HOME/google-cloud-sdk/path.bash.inc
        gcloud --version

    # Authenticate with Google Cloud service account
    - name: Set up Google Cloud service account
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/service_account_key.json
        # Check if the JSON key is properly written
        cat /tmp/service_account_key.json
        gcloud auth activate-service-account --key-file=/tmp/service_account_key.json

    # Set up environment variables and DBT profile with us-central1 location
    - name: Set up DBT profile for BigQuery
      run: |
        mkdir -p ~/.dbt
        echo "dbt_github_action:
          target: dev
          outputs:
            dev:
              type: bigquery
              project: dbt-learning-bq
              dataset: dbt
              threads: 1
              keyfile: /tmp/service_account_key.json
              location: us-central1" > ~/.dbt/profiles.yml

    # Run DBT models
    - name: Run DBT models
      run: |
        dbt run --profiles-dir ~/.dbt
