name: Run DBT Models on GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install DBT and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-bigquery google-cloud google-auth google-auth-oauthlib google-auth-httplib2

    # Authenticate using Google Auth Library (Python)
    - name: Authenticate with Google Cloud (Python)
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/service_account_key.json
        python -c "
        import json
        from google.oauth2 import service_account
        from google.auth.transport.requests import Request
        import google.auth

        # Load credentials from the JSON key
        with open('/tmp/service_account_key.json') as key_file:
              credentials = service_account.Credentials.from_service_account_info(
                json.load(key_file), scopes=['https://www.googleapis.com/auth/cloud-platform'])

        # Check the credentials are working by refreshing them
        credentials.refresh(Request())
        "

    # Set up DBT profile
    - name: Set up DBT profile for BigQuery
      run: |
        mkdir -p ~/.dbt
        echo "your_project_name:
          target: dev
          outputs:
            dev:
              type: bigquery
              project: your-gcp-project-id
              dataset: your_bigquery_dataset
              threads: 1
              keyfile: /tmp/service_account_key.json
              location: us-central1" > ~/.dbt/profiles.yml

    # Run DBT models
    - name: Run DBT models
      run: |
        dbt run --profiles-dir ~/.dbt
