name: Run DBT Models on GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # dbt install
    - name: Install DBT and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-bigquery google-cloud

    # Authenticate using the service account key from GitHub Secrets
    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }} # Your service account key stored in GitHub Secrets

    # Set up Google Cloud CLI
    - uses: google-github-actions/setup-gcloud@v0.9.1
      with:
        project_id: ${{ env.PROJECT_ID }}  # Ensure you have set PROJECT_ID as an environment variable or in secrets
        export_default_credentials: true

    # Set up DBT profile for BigQuery
    - name: Set up environment variable for DBT profile
      run: |
        mkdir -p ~/.dbt
        echo "keyfile: /tmp/service_account_key.json" > ~/.dbt/profiles.yml
        echo "project: your-gcp-project-id" >> ~/.dbt/profiles.yml
        echo "dataset: your_bigquery_dataset" >> ~/.dbt/profiles.yml
        echo "threads: 1" >> ~/.dbt/profiles.yml
        echo "location: us-central1" >> ~/.dbt/profiles.yml

    # Run DBT models
    - name: Run DBT models
      run: |
        dbt run --profiles-dir ~/.dbt
